export const API_BASE_URL = 'https://api.camping.care/v21';

export const API_ENDPOINTS = {
	ADMINISTRATIONS: '/administrations',
	FIELDS: '/fields',
	FIELDS_FORMS: '/fields/forms',
	ACCOMMODATIONS: '/accommodations',
	CATEGORIES: '/categories',
	CHANNELS: '/channels',
	CODES: '/codes',
	CONTACTS: '/contacts',
	RESERVATIONS: '/reservations',
	PRICE_CALCULATION: '/price_calculation',
	TIMEZONES: '/timezones',
	WEBHOOKS: '/webhooks',
	WEBHOOKS_EVENTS: '/webhooks/events',
	INVOICES: '/invoices',
	PAYMENTS: '/payments',
	RATES: '/rates',
	LICENSE_PLATES: '/license_plates',
	LOGS: '/logs',
	TAGS: '/tags',
	AVAILABILITY_STOCK: '/availability/stock',
	AVAILABILITY_PLACES: '/availability/places',
	EXCHANGE_RATES: '/exchange_rates',
} as const;

export const EXCLUDED_CONTACT_FIELDS = [
	'gender',
	'first_name',
	'last_name',
	'address',
	'address_number',
	'birthday',
	'city',
	'company',
	'country',
	'country_origin',
	'email',
	'id_nr',
	'phone',
	'zipcode',
	'phone_mobile',
	'vat_number',
	'state',
	'id_type',
	'created',
	'create_date',
] as const;

export const RESOURCES = {
	ACCOMMODATIONS: 'accommodations',
	ADMINISTRATIONS: 'administrations',
	AVAILABILITY: 'availability',
	CATEGORIES: 'categories',
	CONTACTS: 'contacts',
	PRICE_CALCULATION: 'priceCalculation',
	RESERVATIONS: 'reservations',
	TIMEZONES: 'timezones',
	RATES: 'rates',
	INVOICES: 'invoices',
	LICENSE_PLATES: 'licensePlates',
	LOGS: 'logs',
	TAGS: 'tags',
	EXCHANGE_RATES: 'exchangeRates',
} as const;

export const OPERATIONS = {
	GET_ACCOMMODATION: 'getAccommodation',
	GET_ACCOMMODATIONS: 'getAccommodations',
	ADD_ACCOMMODATION: 'addAccommodation',
	UPDATE_ACCOMMODATION: 'updateAccommodation',
	DELETE_ACCOMMODATION: 'deleteAccommodation',

	GET_CATEGORIES: 'getCategories',
	GET_CATEGORY: 'getCategory',
	ADD_CATEGORY: 'addCategory',
	UPDATE_CATEGORY: 'updateCategory',
	DELETE_CATEGORY: 'deleteCategory',

	GET_ADMINISTRATION: 'getAdministration',
	GET_ADMINISTRATIONS: 'getAdministrations',
	UPDATE_ADMINISTRATION: 'updateAdministration',
	ADD_ADMINISTRATION: 'addAdministration',
	DELETE_ADMINISTRATION: 'deleteAdministration',
	AGE_TABLES: 'ageTables',
	GET_AGE_TABLES: 'getAgeTables',
	GET_AGE_TABLE: 'getAgeTable',

	GET_CONTACT: 'getContact',
	GET_CONTACTS: 'getContacts',
	ADD_CONTACT: 'addContact',
	UPDATE_CONTACT: 'updateContact',
	DELETE_CONTACT: 'deleteContact',

	GET_EXCHANGE_RATES: 'getExchangeRates',
	EXCHANGE_VALUE: 'exchangeValue',

	CALCULATE_PRICE: 'calculatePrice',

	GET_RESERVATION: 'getReservation',
	GET_RESERVATIONS: 'getReservations',
	CREATE_RESERVATION: 'createReservation',
	DELETE_RESERVATION: 'deleteReservation',

	GET_TIMEZONES: 'getTimezones',

	GET_RATES: 'getRates',
	GET_RATE: 'getRate',
	ADD_RATE: 'addRate',
	UPDATE_RATE: 'updateRate',
	DELETE_RATE: 'deleteRate',

	GET_LICENSE_PLATES: 'getLicensePlates',
	GET_LICENSE_PLATE: 'getLicensePlate',
	CHECK_VALID_LICENSE_PLATE: 'checkValidLicensePlate',
	ADD_LICENSE_PLATE: 'addLicensePlate',
	UPDATE_LICENSE_PLATE: 'updateLicensePlate',
	DELETE_LICENSE_PLATE: 'deleteLicensePlate',
	PRICES: 'prices',
	GET_PRICES: 'getPrices',
	UPDATE_PRICES: 'updatePrices',
	UPDATE_PRICES_BULK: 'updatePricesBulk',

	META: 'meta',
	GET_META: 'getMeta',
	UPDATE_META: 'updateMeta',
	DELETE_META: 'deleteMeta',

	GET_INVOICES: 'getInvoices',
	GET_INVOICE: 'getInvoice',
	ADD_INVOICE: 'addInvoice',
	UPDATE_INVOICE: 'updateInvoice',
	DELETE_INVOICE: 'deleteInvoice',
	FINALIZE_INVOICE: 'finalizeInvoice',
	CANCEL_DELAYED_FINALIZED_INVOICE: 'cancelDelayedFinalizedInvoice',
	CREATE_CREDIT: 'createCredit',

	GET_LOGS: 'getLogs',
	ADD_LOG: 'addLog',

	GET_STOCK: 'getStock',
	GET_PLACES: 'getPlaces',

	GET_TAGS: 'getTags',
	GET_TAG: 'getTag',
	ADD_TAG: 'addTag',
	DELETE_TAG: 'deleteTag',
} as const;
